name: automation-labels

on:
  pull_request_target:
    types: [opened]

jobs:
  automate-labels:
    concurrency: 
      group: ${{ github.head_ref }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - name: Check organization
        id: get_check_code
        run: |
          http_code=`curl -s --head -I -H "Authorization: token ${{ secrets.ACCESS_TOKEN }}" -H "Accept: application/vnd.github.v3+json" https://api.github.com/orgs/cocos-creator/members/${{ github.event.pull_request.user.login }} | awk '/HTTP/{print $2}'`
          echo "::set-output name=http_code::${http_code}"
      - name: Echo username organization
        run: |
          echo ${{ github.event.pull_request.user.login }}
          echo ${{ steps.get_check_code.outputs.http_code }}
      - name: Add contribution label
        if: |
          steps.get_check_code.outputs.http_code == 404
        uses: OperationsYU/labeler@master
        with:
          add-labels: "contribution"

      - name: assignment
        if: |
          steps.get_check_code.outputs.http_code == 404
        uses: OperationsYU/auto-assignment@v1
        with:
          token: ${{ secrets.LABEl_TOKEN }}
          users: '["minggo"]'
