name: Apply Clang Format

#on: [push, pull_request]
on:
  pull_request:
    types: [closed]

jobs:
  Clang-Format:
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{secrets.GITHUB_TOKEN }}
        ref: ${{ github.head_ref }}
    
    - name: install clang-format
      run: |
        sudo apt-get install clang-format git
    
    - name: apply clang-format
      run: |
        SRC=$(git ls-tree --full-tree -r HEAD | grep -e "\.\(c\|h\|hpp\|cpp\|cxx\)\$" | cut -f 2)
        clang-format -style=file -i $SRC
    
    - uses: fish9167/git-auto-commit-action@v4
      with:
        commit_message: Apply clang-format
        commit_user_name: cocos-robot
        commit_user_email: cocos-robot@cocos.com
        commit_author: cocos-robot <cocos-robot@cocos.com>
        push_options: --force
