name: ðŸ”ƒ Glue

on:
  pull_request_target:
    types: [closed]

jobs:
  generate-jsb:
    if: github.event_name == 'pull_request_target' && github.event.action == 'closed' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download external libraries
        run: |
          EXT_VERSION=`grep version native/external/config.json  |awk -F'"' '{print $4}'`
          rm native/external/config.json
          git clone --branch $EXT_VERSION --depth 1 https://github.com/cocos-creator/engine-native-external native/external
          rm -rf external/.git
          git checkout HEAD external/config.json

      - name: Run genbindings.py
        run: |
          python3 -m pip install PyYAML==5.4.1 Cheetah3
          python3 ./native/tools/tojs/genbindings.py
          rm ./native/tools/tojs/userconf.ini

      - name: Create Pull Request 
        uses: fish9167/create-pull-request@v3
        with:
            title: '[ci skip][AUTO]: Automated PR to genbindings'
            body: |
              Automated PR to genbindings
            committer: cocos-robot <cocos-robot@cocos.com>
            author: cocos-robot <cocos-robot@cocos.com>
            commit-message: "[ci skip][AUTO]: Automated genbindings update: ${{ github.event.pull_request.head.sha }}  (#${{ github.event.number }})"
            token: ${{ secrets.PR_TOKEN }}
            push-to-fork: cocos-robot/cocos2d-x-lite
            branch: t/bot/genbindings
            branch-suffix: short-commit-hash
            delete-branch: true
            milestone: 1
          
      #- name: Make PR
      #  run: |
      #    cd tools/travis-scripts && bash generate-pr.sh
      #  env:
      #    TRAVIS_OS_NAME: linux
      #    TRAVIS_PULL_REQUEST: "false"
      #    TRAVIS_BRANCH: ${{github.base_ref}}
      #    TRAVIS_COMMIT: ${{github.sha}}
      #    TRAVIS_COMMIT_MESSAGE: ${{github.event.head_commit.message}}
      #    GH_EMAIL: cocos-robot@cocos.com
      #    GH_PASSWORD: ${{ secrets.PR_TOKEN }}
      #    GH_TOKEN: ${{ secrets.PR_TOKEN }}
      #    GH_USER: cocos-robot
