name: üñ•Ô∏è Simulator

on: [pull_request]

jobs:
  win_gen_simulator:
    # windows 2019, Visual Studio Enterprise 2019
    # windows 2016, Visual Studio Enterprise 2017
    #runs-on: windows-latest
    runs-on: windows-2016
    name: Windows

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: npm install
        working-directory: ${{github.workspace}}/native
        run: |
          npm install
      - name: download external libraries
        run: |
          node ./native/utils/download-deps.js
      - name: install vulkan-sdk
        run: |
          choco install vulkan-sdk
      - name: pip install
        run: |
          python -m pip install PyYAML==5.4.1 Cheetah3
      - name: install android ndk
        shell: bash
        working-directory: ${{github.workspace}}
        run: |
          curl -O http://dl.google.com/android/repository/android-ndk-r16b-windows-x86_64.zip
          unzip -q android-ndk-r16b-windows-x86_64.zip
          mkdir -p ${HOME}/bin
          mv android-ndk-r16b ${HOME}/bin/android-ndk
          ls ${HOME}
      - name: generate bindings glue codes
        shell: bash
        run: |
          python -V
          export NDK_ROOT=${HOME}/bin/android-ndk
          cd ./native/tools/tojs
          echo "Create auto-generated jsbinding glue codes."
          python ./genbindings.py
          rm userconf.ini
      - name: gen simulator
        run: |
          gulp gen-simulator-release
      - name: check result
        run: |
          Get-ChildItem ./native/simulator/Debug -Name SimulatorApp-Win32.exe
          if(Test-Path ./native/simulator/Debug/SimulatorApp-Win32.exe) {exit 0} else {exit 1}
  # mac_gen_simulator:
  #   runs-on: macos-latest
  #   name: MacOS
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-python@v2
  #       with:
  #         python-version: "3.x"
  #     - name: npm install
  #       run: |
  #         npm install
  #         npm install gulp -g
  #     - name: download external libraries
  #       run: |
  #         node ./native/utils/download-deps.js
  #     - name: pip install
  #       run: |
  #         python -m pip install PyYAML Cheetah3
  #     - name: install android ndk
  #       shell: bash
  #       working-directory: ${{github.workspace}}
  #       run: |
  #         curl -O http://dl.google.com/android/repository/android-ndk-r16b-darwin-x86_64.zip
  #         unzip -q android-ndk-r16b-darwin-x86_64.zip
  #         mkdir -p  ${HOME}/bin
  #         mv android-ndk-r16b ${HOME}/bin/android-ndk
  #         ls ${HOME}
  #     - name: generate bindings glue codes
  #       shell: bash
  #       run: |
  #         python -V
  #         export NDK_ROOT=${HOME}/bin/android-ndk
  #         cd ${{github.workspace}}/tools/travis-scripts
  #         echo "Create auto-generated jsbinding glue codes."
  #         pushd ${{github.workspace}}/native/tools/tojs
  #         python ./genbindings.py
  #         rm userconf.ini
  #         popd
  #     - name: gen simulator
  #       run: |
  #         gulp gen-simulator-release
  #     - name: check result
  #       run: |
  #         find ./ -name SimulatorApp-Mac
  #         [ -f ./native/simulator/Debug/SimulatorApp-Mac.app/Contents/MacOS/SimulatorApp-Mac ] && exit 0 || exit 1
