name: <Web> Check version

#on: push
on: [create, pull_request]

jobs:
  Check_pull_request_version:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v2

      - name: npm install
        run: |
          node -v
          npm install || exit 0
          
      - name: check version
        run: |
          branch=`echo ${{ github.base_ref }} | awk -F'/' '{print $NF}'`
          echo "Branch： ${branch}"
          npm run varify-engine-version -- ${branch}
          
  Check_create_version:
    runs-on: ubuntu-latest
    if: github.event_name == 'create'
    steps:
      - uses: actions/checkout@v2
  
      - name: npm install
        run: |
          node -v
          npm install || exit 0
      - name: check version
        run: |
          branch=`echo ${{ github.ref }} | awk -F'/' '{print $NF}'`
            echo "Branch： ${branch}"
            npm run varify-engine-version -- ${branch}
            
