name: <Web> npm test

on: [push, pull_request]

# github.head_ref is only defined on pull_request events
concurrency:
  group: ${{ github.workflow }}-${{ github.actor }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  npm_test:
    if: 
      (! contains(github.event.pull_request.body, '[X] does not change any runtime related code or build configuration'))
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: '14.19'

    - name: install gulp
      run: |
        npm install -g gulp
        
    - name: Download external
      run: |
        EXT_VERSION=`node ./.github/workflows/get-native-external-version.js`
        git clone --branch $EXT_VERSION --depth 1 https://github.com/cocos/cocos-engine-external native/external

    - name: npm install
      run: |
        npm install
       
    - name: build-debug-infos
      run: |
        gulp build-debug-infos
        
    - name: run test
      run: |
        export NODE_OPTIONS="--max-old-space-size=8192"
        npm test
